# Generated by Django 4.1.7 on 2023-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('header', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
